### ISSUE TITLE
Where's OpenDyslexic?

### ISSUE THREAD

**Issue by waldyrious** [elementary/fonts#2] opened 2018-01-10 11:43 UTC
[Bug #1405900 on Launchpad](https://bugs.launchpad.net/elementaryos/+bug/1405900) was closed a while ago as "Fix Released", but there's no mention of it in this repo. Shouldn't there be?

**Comment by lewisgoddard** [comment] 2018-01-10 20:49
The only references I find to that since moving to GitHub is these: 

1. [elementary/fonts `debian/control` Line 58](https://github.com/elementary/fonts/blob/master/debian/control#L58) seems to imply the package is a dependency of the `fonts-elementary-extra` metapackage, which implies **it is delivered upstream as `fonts-opendyslexic`**.

2. [elementary/switchboard-plug-a11y `src/Backend/Settings.vala` Line 21](https://github.com/elementary/switchboard-plug-a11y/blob/master/src/Backend/Settings.vala#L21) is a TODO item that seems to show intent to implement some kind of switch in the accessibility plug.

I have made no attempt to install it and it does appear on my system (in Loki 0.4.1).

**Comment by danirabbit** [comment] 2018-01-11 00:10
I can confirm OpenDyslexic is present on the latest ISO. Closing

**Closed as completed by danirabbit** 2018-01-11 00:10 UTC

**Comment by waldyrious** [comment] 2018-05-22 10:55
> I have made no attempt to install it and it does appear on my system (in Loki 0.4.1).

Indeed, `fc-list | grep -i dyslexic` returns several results for me as well.
